# Generated by Django 2.0.5 on 2018-08-05 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img_file', models.ImageField(upload_to='images')),
                ('card_description', models.CharField(blank=True, max_length=200)),
                ('prediction', models.CharField(blank=True, max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('actual_total_prod', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dysfunction_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dys_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dys_description', models.CharField(blank=True, max_length=50, null=True)),
                ('dys_action', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pumping_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.CharField(choices=[('1', 'Wolfbone RMT'), ('2', 'Lockridge RMT'), ('3', 'Cedar Canyon RMT'), ('4', 'Mentone RMT'), ('5', 'FDP'), ('6', 'Well Analysis and Design')], default='Wolfbone RMT', max_length=100)),
                ('asset', models.CharField(choices=[('WOLFBONE', 'Wolfbone'), ('REDBULLSOUTH', 'RedBull South'), ('LOCKRIDGE', 'Lockridge'), ('MENTONE', 'Mentone'), ('HELLSCANYON', 'Hells Canyon'), ('REDBULLNORTH', 'RedBull North')], default='Wolfbone', max_length=100)),
                ('region', models.CharField(choices=[('TXDELAWARE', 'Tx Delaware Basin'), ('MIDLAND', 'Midland Basin'), ('NMDEL', 'NM Delaware Basin')], default='Tx Delaware Basin', max_length=100)),
                ('subwelltype', models.CharField(choices=[('WCA10k', 'WCA_10k'), ('WCA7.5k', 'WCA_7500'), ('1BS10k', '1BS_10k'), ('WCB10k', 'WCB_10k'), ('WCC10k', 'WCC_10k'), ('2BS10k', '2BS_10k'), ('3BS10k', '3BS_10k'), ('HOBAN10k', 'Hoban_10k'), ('HOBAN5k', 'Hoban_5k')], default='WCA_10k', max_length=50)),
                ('designed_total_prod', models.IntegerField(default=0, null=True)),
                ('last_well_test', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('engineer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card_info',
            name='associated_well_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyno.Well_Profile'),
        ),
    ]
